export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAILURE = 'FETCH_ALBUMS_FAILURE';
export const SORT_BY_TITLE_ASC = 'SORT_BY_TITLE_ASC';
export const SORT_BY_TITLE_DESC = 'SORT_BY_TITLE_DESC';
export const SORT_BY_RATING_ASC = 'SORT_BY_RATING_ASC';
export const SORT_BY_RATING_DESC = 'SORT_BY_RATING_DESC';
export const FILTER_BY_SEARCH_QUERY = 'FILTER_BY_SEARCH_QUERY';
export const TOGGLE_SEARCH_ACTIVE = 'TOGGLE_SEARCH_ACTIVE';
